[tool.black]
line-length = 88
target-version = ['py310']

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.5.6"
tag_format = "v$version"
version_files = [
    "src/__init__.py",
    "pyproject.toml:version"
]

[tool.semantic_release]
version_variables = ["src/__init__.py:__version__"]
version_toml = ["pyproject.toml:tool.commitizen.version"]
major_on_zero = false
branch = "main"
upload_to_pypi = false
upload_to_release = true